ElasticNet:
  alpha: 0.2
  l1_ratio: 0.1

RandomForestClassifier:
  n_estimators: 100  # Number of decision trees in the forest
  max_depth: None    # Maximum depth of each tree (None means unlimited)
  min_samples_split: 2  # Minimum number of samples required to split a node

XGBClassifier:
  n_estimators: 100  # Number of boosting rounds
  max_depth: 3       # Maximum depth of each tree in the ensemble
  learning_rate: 0.1 # Learning rate (controls the contribution of each tree)